on:
  push:
    branches:
      - main

name: Build and Deploy to Cloud Run
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SERVICE: sf-demo-repo
  REGION: us-east1

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub Login
        env:
          DOCKER_USER : ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Build
        run : |-
          docker build -t bobput/sf-demo-ui:latest .
          docker build -t bobput/sf-demo-ui:${{ github.sha }} .
      - name: Docker Push
        run : |-
          docker push bobput/sf-demo-ui:latest
          docker push bobput/sf-demo-ui:${{ github.sha }}
    